---
name: Linter
on:
  push: null
  pull_request: null
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: HCL AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
